Resources:
# S3 Bucket
  nasBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: www.leopard.nasfinancialgroup.com
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders:
          - "*"
          AllowedMethods:
          - GET
          AllowedOrigins:
          - "*"
          Id: Staticweb
          MaxAge: 60
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  nasBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref nasBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref nasBucket
                - /*
            Principal: '*'
